### ISSUE TITLE
addmagazinecargo.txt yellow smoke grenades

### ISSUE THREAD

**Issue by fazmond** [DayZMod/Battleye-Filters#130]
when trying to put a yellow grenade in a tent it would kick
so I changed the code from 1 to 2 to test and it 
will not let a player take the yellow smoke out of the tent so there is a problem here some where 
please help :P

**Comment by GeryonTom** [comment]
It would help if you provided the addmagazinecargo.log line that resulted in the kick.  Also are you running pure vanilla?

**Comment by fazmond** [comment]
pure vanillia
i'll see if I can find it

**Comment by fazmond** [comment]
06.06.2015 17:01:44: ####PLAYER IP HIDDEN ######- #0 "SmokeShellYellow" 0:0

and also found this 

06.06.2015 10:42:36: ####PLAYER IP HIDDEN ######- #1 "10Rnd_127x99_m107" 0:0

**Comment by GeryonTom** [comment]
Okay I think I know what's happening.  It looks like you have some old objects from the legacy vehicle spawn.  Certain vehicles had SmokeShellYellow and M107 magazines.  I would tell the players to not use the Yellow smoke since they don't naturally spawn in the game.  M107 I'd ditch them since there's no 50 caliber weapons and even if there were they would do 0 damage.

Temporarily change the following text in your filter from:
!=SmokeShell(Red|Green)?

to

!=SmokeShell(Red|Green|Yellow)?

However the official filters shouldn't have Yellow whitelisted.

**Comment by fazmond** [comment]
well I added that and they guys still cant take it out of his tent
ive removed the items from spawning in the vheicals spawn list thou
also our players backpacks are disappearing on a server restart I think I had a smoke grenade in the pack

**Comment by GeryonTom** [comment]
There's a hot fix for the backpacks: https://dayzmod.slack.com/files/r4z0r49/F061KDV0W/dayz_1337.chernarus-1.6.8.2.rar

Not sure why you can't take them out.  Also make sure the filter is 5 (log and kick).

**Comment by R4Z0R49** [comment]
The backpack issue is being worked on server admins in slack do have a test mission file thats being tested. Once its all tested and verified we will push to everyone else in the normal fashion.

**Comment by fazmond** [comment]
ok R4Z0R49

GreyonTom he couldn't remove it cause when I checked the data base it wasn't in his stash and was gone after a server restart

**Comment by ebayShopper** [comment]
As mentioned these items don't spawn in vanilla normally, so you have to add your own exceptions if you want to use them.
