### ISSUE TITLE
Limit of remotexec 

### ISSUE THREAD

**Issue by CrackH34D** [DayZMod/Battleye-Filters#134]
Hi is there a Limit for remotexec.txt because we can not put any more Filters they get still Kicker of

**Comment by ebaydayz** [comment]
Post your remoteexec.txt.

The first line kicks for everything, so you need to add it as an exception on that one. The second line kicks again for all special characters, so you would need to add it as an exception on that one too if it contained any of those.

The second line should not be needed, because the first line already covers everything on it. Why was it added @facoptere ? https://github.com/DayZMod/Battleye-Filters/commit/e58100b4fbe6b6d8aa76f8758d6d2647b6a2eeda
